export enum Onboarding {
  USER_AGREEMENT_PENDING = 'USER_AGREEMENT_PENDING',
  PHRASE_AND_SECURITY_PENDING = 'PHRASE_AND_SECURITY_PENDING',
  BIOMETRIC_SETUP_PENDING = 'BIOMETRIC_SETUP_PENDING',
  COMPLETE = 'COMPLETE',
}
